### ISSUE TITLE
Revert to using the official isort repo

### ISSUE THREAD

**Issue by jsf9k** [cisagov/log4j-md-yml#2]
# 💡 Summary #

We are currently being bitten by PyCQA/isort#1874.  In commit 51752ee I switched to using the `isort` branch referenced in PyCQA/isort#1875, which was created to resolve PyCQA/isort#1874.  Once PyCQA/isort#1875 is merged we should revert commit 51752ee.

## Motivation and context ##

Once PyCQA/isort#1875 is merged the underlying branch could disappear at any moment, and in general it is better to use official sources wherever it is at all possible.

**Comment by mcdonnnj** [comment]
@jsf9k Are we good to close this per 57680bf?

**Comment by dav3r** [comment]
@mcdonnnj I just added  a "Resolves #2" to PR #1.
